version: '3.8'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: dkm
      POSTGRES_PASSWORD: dkm
      POSTGRES_DB: dkm
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dkm"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./server/dockerfile
    ports:
      - "5001:5001"
    env_file: .env
    environment:
      - POSTGRES_CONNECTION=postgres://dkm:dkm@db:5432/dkm
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./dkm
      dockerfile: dockerfile
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5001
    ports:
      - "3000:3000"
