version: '3.8'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: dkm
      POSTGRES_PASSWORD: dkm
      POSTGRES_DB: dkm
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./server/dockerfile
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./dkm
      dockerfile: dockerfile
    ports:
      - "3000:3000"
