FROM golang:1.22-alpine AS builder

WORKDIR /go/src/app

COPY . .

# get go stuff
RUN go get github.com/mattn/go-isatty@v0.0.19

RUN go build -o main .

# copy over env and run go app
FROM alpine:latest
WORKDIR /app
COPY --from=builder /go/src/app/main .
COPY --from=builder /go/src/app/.env .

CMD ["./main"]
