FROM golang:1.22-alpine AS builder

WORKDIR /go/src/app

COPY . .

RUN go get github.com/mattn/go-isatty@v0.0.19

# Build the Go app
RUN go build -o main .

# Final stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /go/src/app/main .
COPY --from=builder /go/src/app/.env .

CMD ["./main"]
